services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
